### ISSUE TITLE
添加对[戳一戳]互动的延迟

### ISSUE THREAD

**Issue by ll11l1lIllIl1lll** [BakaBotTeam/lgz-bot#5]
**您的功能请求与问题有关吗？ 请描述。**
有人开模块 一秒戳30下 导致bot会刷屏 很致癌

**描述您想要的解决方案**
添加一个延迟，比如在100ms内最多可以回应多少个[戳一戳]

**描述您考虑过的替代方案**
\-

**其他上下文**
\-

**Comment by guimc233** [comment]
在线demo的戳一戳功能由其他插件提供
由于[原仓库](https://github.com/LaoLittle/AutoGroup)已归档 我们会考虑fork下来进行修改

**Comment by guimc233** [comment]
已尝试解决 https://github.com/BakaBotTeam/lgz-bot/commit/9b8e010f01a932823e1fed400d026c5c441e0d6a
若未解决 请重新打开Issues

**Comment by guimc233** [comment]
已解决 测试可用
